data:
  raw_path: "data/ecg_data_raw.csv"
  clean_path: "data/ecg_data_clean.csv"
  features:
    - rr_interval
    - p_onset
    - p_end
    - qrs_onset
    - qrs_end
    - t_end
    - p_axis
    - qrs_axis
    - t_axis
  label: "Healthy"
  split:
    test_size: 0.15
    dev_size: 0.15
    random_state: 42

prompts:
  simple: "promts/1.dat"
  detailed: "promts/2.dat"
  chain_of_thought: "promts/3.dat"
  medical_english: "promts/4.dat"

models:
  sklearn_methods:
    - name: "LogisticRegression"
      type: "sklearn"
      module: "sklearn.linear_model"
      class: "LogisticRegression"
      params:
        C: 1.0
        max_iter: 1000
        random_state: 42
        class_weight: "balanced"

    - name: "KNN"
      type: "sklearn"
      module: "sklearn.neighbors"
      class: "KNeighborsClassifier"
      params:
        n_neighbors: 7
        weights: "distance"

    - name: "RandomForest"
      type: "sklearn"
      module: "sklearn.ensemble"
      class: "RandomForestClassifier"
      params:
        n_estimators: 300
        max_depth: 15
        min_samples_split: 5
        class_weight: "balanced"
        random_state: 42

    - name: "XGBoost"
      type: "sklearn"
      module: "xgboost"
      class: "XGBClassifier"
      params:
        n_estimators: 300
        learning_rate: 0.05
        max_depth: 8
        use_label_encoder: false
        eval_metric: "logloss"
        scale_pos_weight: 2.7

  llm_methods:
    - name: "RuBERT_Chat_Simple"
      type: "llm_chat"
      model_name: "DeepPavlov/rubert-base-cased"
      prompt_key: "simple"
      device: 0

    - name: "RuBERT_Chat_Detailed"
      type: "llm_chat"
      model_name: "DeepPavlov/rubert-base-cased"
      prompt_key: "detailed"
      device: 0

    - name: "RuBERT_Chat_CoT"
      type: "llm_chat"
      model_name: "DeepPavlov/rubert-base-cased"
      prompt_key: "chain_of_thought"
      device: 0

    - name: "RuBERT_FineTuned"
      type: "llm_finetune"
      model_name: "DeepPavlov/rubert-base-cased"
      prompt_key: "simple"
      device: 0

    - name: "XLM_RoBERTa_Chat"
      type: "llm_chat"
      model_name: "xlm-roberta-base"
      prompt_key: "detailed"
      device: 0

    - name: "BiomedBERT_Chat"
      type: "llm_chat"
      model_name: "microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract"
      prompt_key: "medical_english"
      device: 0

    - name: "ClinicalBERT_Chat"
      type: "llm_chat"
      model_name: "emilyalsentzer/Bio_ClinicalBERT"
      prompt_key: "medical_english"
      device: 0

    - name: "Rule_Based"
      type: "rule_based"

experiments:
  results_csv: "results.csv"
